# Generated by Django 5.2.5 on 2025-08-12 15:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
